### ISSUE TITLE
Removing "Selling your modules" from docs

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/docs#1108]
With the separation of the company and the project, we need to remove docs about Addons: https://devdocs.prestashop.com/1.7/modules/sell/

**Comment by matks** [comment]
ping @Quetzacoalt91 

@Progi1984 is right: we'll have to remove the "Selling" section in the future.

Where do you think it should go? Maybe doc.prestashop.com ?

**Comment by Quetzacoalt91** [comment]
Thanks for letting me know. That's a topic we need to see with the proper Squad, as they may be already building a better version of this documentation.

I'm checking this internally.

**Comment by Quetzacoalt91** [comment]
However, some content should be kept / reworded as they can be even useful in the open source side. Some rules we provide are meant to have better modules for the community.

**Comment by Progi1984** [comment]
Here is a new PR (from @PrestaEdit) which should be in PrestaShopCorp docs and not in open source docs : https://github.com/PrestaShop/docs/pull/1137#pullrequestreview-749990005

**Comment by matks** [comment]
Hello @intraordinaire I believe this is one topic you will have to face soon 😄

**Comment by intraordinaire** [comment]
> Hello @intraordinaire I believe this is one topic you will have to face soon 😄

Indeed !
This issue is well linked here already, so it's in my "todo" 😅

**Comment by intraordinaire** [comment]
After a quick look on these pages : 
_[Selling you modules (index)](https://devdocs.prestashop.com/1.7/modules/sell/)_ & _[Technical tools](https://devdocs.prestashop.com/1.7/modules/sell/technical-tools/)_ : can be removed from core project doc, as it only mention validator, module generator & how to submit modules.
The other pages _[Technical Validation: key steps](https://devdocs.prestashop.com/1.7/modules/sell/techvalidation-keysteps/)_ & _[Validation checklist](https://devdocs.prestashop.com/1.7/modules/sell/techvalidation-checklist/)_ are more rules and info in order to have better modules, and can be moved/renamed in my opinion.

**Comment by matks** [comment]
> After a quick look on these pages : _[Selling you modules (index)](https://devdocs.prestashop.com/1.7/modules/sell/)_ & _[Technical tools](https://devdocs.prestashop.com/1.7/modules/sell/technical-tools/)_ : can be removed from core project doc, as it only mention validator, module generator & how to submit modules.

Can we do this now, or do we wait for you to open a 'PrestaShop SA modules doc' to transfer the knowledge?

**Comment by intraordinaire** [comment]
I've moved these pages to the validator project for now.
The [PR is here](https://github.com/PrestaShopCorp/validator/pull/95).
So, I think we can proceed with this update here.
