### ISSUE TITLE
How to add a translation into Russian?

### ISSUE THREAD

**Issue by ivanscm** [PrestaShop/docs#130]
I translate the documentation. What do you need to do to get the documentation to the main site?

**Comment by eternoendless** [comment]
Hi @ivanscm 

Thanks for your proposal! In order to ensure that everyone has the most updated version of technical documentation available, we aren't thinking on translating it to other languages. We assume that all developers have at least a basic understanding of English.

However, the [user documentation](http://doc.prestashop.com/display/PS17/PrestaShop+1.7+documentation) is available in several languages. If you are interested in translating that, I think @LouiseBonnard may be able to help you!

**Comment by LouiseBonnard** [comment]
Dear @ivanscm, if this request is about the user documentation, please write an email to louise.bonnard@prestashop.com with all the details, I'll see what I can do to help, thanks!
