### ISSUE TITLE
Improve PS version selector

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/docs#1635]
When we change PS version with selector in left column, we are redirected to documentation summary.
I think we should stay on the current page (if it exists in other documentation version).

**Comment by micka-fdz** [comment]
> Warning: You are browsing the documentation for PrestaShop 1.7, which is outdated.
> You might want to read an [updated version of this page] for the current version, PrestaShop 8.

Maybe we can do like on "updated version of this page" link.

**Comment by kpodemski** [comment]
cc @thomasnares 

it would be an interesting improvement 👍🏻

**Comment by thomasnares** [comment]
👍 yes, will think about it, it should be possible

**Comment by micka-fdz** [comment]
Thanks @thomasnares, keep in touch 👍

**Comment by thomasnares** [comment]
Fixed by https://github.com/PrestaShop/ps-docs-theme/pull/28, thanks @micka-fdz

**Comment by thomasnares** [comment]
A small but interesting improvement we could do :

In the case of non existant page on other version,
loop through parents of current url, until we find a matching path: 

Targeting 8.x doc, if we are on 1.7.x doc, and on page: 

/1.7/modules/core-updates/1.7.8/

-> page /8/modules/core-updates/1.7.8/ does not exist
-> page /8/modules/core-updates/ does exist -> link to this page instead of /8/

What do you think about it?

**Comment by kpodemski** [comment]
@thomasnares sounds good

**Comment by micka-fdz** [comment]
@thomasnares sounds good to me too 👍

**Comment by kpodemski** [comment]
we will stay with the current solution for the moment :)

**Comment by thomasnares** [comment]
Found a solution during my sleep :)
