### ISSUE TITLE
Explain main FrontEnd classes roles

### ISSUE THREAD

**Issue by prestarocket** [PrestaShop/docs#39]
New version come with a lot of change; for example, in module ps_featuredproducts, you use 
use PrestaShop\PrestaShop\Core\Module\WidgetInterface;
use PrestaShop\PrestaShop\Adapter\Category\CategoryProductSearchProvider;
use PrestaShop\PrestaShop\Adapter\Image\ImageRetriever;
use PrestaShop\PrestaShop\Adapter\Product\PriceFormatter;
use PrestaShop\PrestaShop\Core\Product\ProductListingPresenter;
use PrestaShop\PrestaShop\Adapter\Product\ProductColorsRetriever;
use PrestaShop\PrestaShop\Core\Product\Search\ProductSearchContext;
use PrestaShop\PrestaShop\Core\Product\Search\ProductSearchQuery;
use PrestaShop\PrestaShop\Core\Product\Search\SortOrder;

It s very hard to understand... could you provide an explanation step by step ?

**Comment by matks** [comment]
Hi @prestarocket I renamed this issue to "Explain main FrontEnd classes roles" as, it seems to me, this is what this issue is about.

Is this issue still relevant ? I think the frontend can be better explained, but I'm not sure we need an explanation of each of these classes ? I mean, without checking it, I'd say ImageRetriever role is to retrieve images. Maybe what would be better instead would be a mapping of "who calls who" ?

Also since this issue has been opened in 2016, I guess you have obtained the answer since this time. Would you consider contributing to the docs with your knowledge ?

I'm not saying this in order to make you work for us 😄but if I write this doc, I will write it from a core developer point of view, not from a prestashop user point of view.

You can also just tell me "ok, I think you need to explain things A, B and C" and I'll write it 😉what I'm interested in is "what, from your point of view, was not clear at this time"

**Comment by matks** [comment]
Closing as it seems author moved away from this topic
