### ISSUE TITLE
Theme / Email templates: document the "Email generator" modules

### ISSUE THREAD

**Issue by xBorderie** [PrestaShop/docs#46]
Updating the design of emails is a pain for developers, most notably because header and footer cannot be included as-is.

We at PrestaShop have built specific modules for that:

* 1.6: https://github.com/PrestaShop/emailgenerator
* 1.7: https://github.com/PrestaShop/ps_emailgenerator

It's high time we document them properly!

**Comment by xBorderie** [comment]
Could https://github.com/PrestaShop/email-templates-sdk be added to such a doc, @Scritik ?
Or are the two unrelated?

**Comment by Scritik** [comment]
Yes it's related :)

The SDK is an improved version by the way. You can have custom variables, partials, ect, but you will need a module to install the templates.

**Comment by xBorderie** [comment]
Could the improvement parts of the SDK be submitted as PRs to each module?

**Comment by Scritik** [comment]
No, it's a all new module.

When I say improvement, it's about the possibilities.

So, do we really need a documentation on these modules since we have a documented SDK? I see the emailgenerator more as a tool for the native emails. The SDK is here to open external contributions, improve the compatibility with email clients thanks to MJML, and much more. No? :)
And I think that someday, maybe, the SDK can replace the emailgenerator.

**Comment by xBorderie** [comment]
That's a conversation to have with the Core developers, I think :)

**Comment by Scritik** [comment]
I know! @maximebiloe is aware of this, to ping me when discussions about emails are starting.

But again, do we really need a doc on this since the SDK is documented and the module (to install the templates) will be released shortly? Just to save you time :)

**Comment by xBorderie** [comment]
You know more about that module release date than I do, it seems ;)

**Comment by Scritik** [comment]
Well, I'm working on it so... :)

**Comment by matks** [comment]
I think this has been fixed
https://devdocs.prestashop.com/1.7/modules/concepts/mail-templates/
https://devdocs.prestashop.com/1.7/development/components/mail-templates/
