### ISSUE TITLE
Explain how to rebase a PR and why it's necessary

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#500]
Because there is a huge number of PRs merged every day, it's quite common for PRs to have git conflicts. However when we ask the author to rebase them, quite often authors do not know what a git rebase is.

We should explain
- how to do a git rebase
- workarounds to do them (like creating a new branch and cherry-picking previous commits)
- explain why rebases are needed, why git conflicts happen so easily
- acknowledge this is hard to do but it's standard for a project this huge (ping @PierreRambaud you confirm that git conflicts are expected frequently on such a big project ?)

**Comment by eternoendless** [comment]
This has been explained here a long time ago: https://build.prestashop.com/howtos/misc/rebasing-your-git-branch/

**Comment by PierreRambaud** [comment]
I'm not in favor of documenting how git is working.

1 - Already explained by many people who know git better than us (https://git-scm.com/book/en/v2/Git-Branching-Rebasing)
2 - Cherry picking commits is a bad idea to avoid failed `git rebase`, a commit should be a state in the program and represent something without anomalies / bugs
3 - If you start to explain why rebases are needed, you should talk about squash and many others things.
4 - It depends, we have conflicts on 1.7.7.x because of assets and problems with the Order page. People are working on the same thing and because it's a migration, we copy / paste many things (which is totally legit and logic, but provide a bad split of code (Cyclomatic complexity, moire than 10 lines per functions, etc).

if you start to document every tools that are already documented on the Internet to develop on PrestaShop, you'll spend all your days maintaining this repository..
People are able to find everything they wanted with http://google.fr :thinking:

**Comment by matks** [comment]
And yet we have people still surprised when we ask for rebases on a PR with conflict 😄.

I did not plan to explain the complete git rebase story (indeed I wanted to provide a link for already existing tutorials) but rather
- explain git rebase for PrestaShop project
- explain why it's necessary although complex (like I did [for git PR workflow](https://dev.to/mathieuks/introduction-to-github-fork-workflow-why-is-it-so-complex-3ac8))

**Comment by PierreRambaud** [comment]
They are surprised maybe because they never worked on open source projects and are accustomed to push without reviews and tests.

`git rebase` for PrestaShop = `git rebase` for all projects 

We have already too much things to do, why wasting our time to explain something already explained in the Internet :/ 

Should we add a documentation about how to find something on Google :trollface: 

https://lmgtfy.com/?q=git+rebase+example

**Comment by matks** [comment]
> They are surprised maybe because they never worked on open source projects and are accustomed to push without reviews and tests.

Yes, but these people are newbies about using git and github, but they might be PrestaShop experts who have valuable knowledge to share and contribute. I would like to help them to bridge the gap between "I have never contributed to an open source project" to "I can contribute on PS". PrestaShop is a public-friendly solution, let's admit it. We provide a click-and-run ZIP file to install it. We'll have theme integrators willing to contribute, newbie module developers, junior backend developers.

**Comment by matks** [comment]
Since we cannot agree on this topic I think I'll write an article on dev.to (like I did for github workflow) and submit a PR to only link the article 😉it will not be an official part of the doc (and consequently we will not have to maintain / update it), is it alright @PierreRambaud ?

**Comment by PierreRambaud** [comment]
You're also able to do it on the devdoc, I'm not the decider :sweat_smile: 
I just don't want to maintain this kind of documentation :/

**Comment by kpodemski** [comment]
IMO it would be good enough to have predefined reply with:
- information about why you need to rebase
- how to rebase (with URL to some article/tutorial)

I agree with @PierreRambaud that it's not really a "PrestaShop thing", rebasing is hard at first but predefined reply with some help should be good enough :)

btw. i see that https://build.prestashop.com/howtos/misc/rebasing-your-git-branch/ is based on my case ;D and it seems that this article has all we need :D

**Comment by matks** [comment]
Done on dev.to https://dev.to/mathieuks/what-it-means-to-rebase-a-pull-request-submitted-on-github-5717

I think ttoine added a link to it in the devdocs
