### ISSUE TITLE
Upgrade doc is outdated

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#657]
https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/#file-copy

"File copy" step is obvisouly outdated, a `cp -R` will not remove files removed between 2 releases.
This creates issues
- when removing old files such as legacy controlles migrated to Symfony
- when removing unsecure files that have been reported as vulnerability

**Comment by matks** [comment]
Big thanks to @elboletaire for reporting this

**Comment by eternoendless** [comment]
AFAIK the autoupgrade process never removes existing files

**Comment by matks** [comment]
> AFAIK the autoupgrade process never removes existing files

I knew the modules upgrade process does not remove existing files. It's the same for autoupgrade ?

**Comment by PierreRambaud** [comment]
We should prefer `rsync` instead of `cp` but depends on which directories. :thinking:

**Comment by PierreRambaud** [comment]
If we remove unused directories / files we will have a bad time because it will remove modules, themes, custom directories, upload files, download, etc. This is maybe why they choose to use the `cp` command instead.

**Comment by cruftex** [comment]
New Presta user here. Just did my first upgrade from 8.0.0 to 8.0.1. When reading the documentation I figured out that this is rather incomplete and probably makes no sense at all. So I used the upgrade module.

Further investigating the problem, I realize that major relevant things for a proper upgrade is in the code of the upgrademodule and not present in PS core. E.g. the SQL scripts for database migrations:
https://github.com/PrestaShop/autoupgrade/tree/dev/upgrade/sql

The page also says further down that the upgrade procedure from the module needs to be run.

That is a surprise, since the module name is autoupgrade, but its needed for any upgrade.

Suggestions:
- Start with prerequisites and say that the autoupgrade module is needed 
- Maybe add an outdated warning
