### ISSUE TITLE
Problems deleting categories

### ISSUE THREAD

**Issue by PerezHuguet** [PrestaShop/docs#805]
When trying to delete the categories Prestashop 1.7 does not delete them, returning again when pressing the delete button to the categories page I see the ones I want to delete.

If I've noticed that the delete button appears outside the white box that contains all the information where it indicates the options for the products.

**Comment by matks** [comment]
Hi @PerezHuguet sorry for the late answer.

I checked and I can't reproduce your issue in PS 1.7.7.3. I think the issue is likely to come from your environment, maybe a module you installed.

If you need help with your shop or third-party modules, please have a look at the PrestaShop Company’s support plans https://www.prestashop.com/support
